import type { Abi } from "viem"

export const abi: Abi = [
  {"type":"constructor","inputs":[{"name":"initialOwner","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"ACTION_PAUSE_POSITIONS","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"ACTION_REDUCE_LEVERAGE","inputs":[],"outputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"stateMutability":"view"},
  {"type":"function","name":"COOLDOWN_PERIOD","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"lastActionTimestamp","inputs":[{"name":"","type":"bytes32","internalType":"bytes32"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"lastPriceSnapshot","inputs":[{"name":"","type":"address","internalType":"address"}],"outputs":[{"name":"price","type":"uint256","internalType":"uint256"},{"name":"timestamp","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"proposeAction","inputs":[{"name":"actionType","type":"bytes32","internalType":"bytes32"},{"name":"actionData","type":"bytes","internalType":"bytes"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"protocol","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"sentinel","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"setProtocol","inputs":[{"name":"_protocol","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setSentinel","inputs":[{"name":"_sentinel","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"updatePriceSnapshot","inputs":[{"name":"asset","type":"address","internalType":"address"},{"name":"price","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"ActionExecuted","inputs":[{"name":"actionType","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"actionData","type":"bytes","indexed":false,"internalType":"bytes"}],"anonymous":false},
  {"type":"event","name":"ActionProposed","inputs":[{"name":"actionType","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"proposer","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"ActionRejected","inputs":[{"name":"actionType","type":"bytes32","indexed":true,"internalType":"bytes32"},{"name":"reason","type":"string","indexed":false,"internalType":"string"}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true,"internalType":"address"},{"name":"newOwner","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"ProtocolSet","inputs":[{"name":"newProtocol","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"SentinelSet","inputs":[{"name":"newSentinel","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"SnapshotUpdated","inputs":[{"name":"asset","type":"address","indexed":true,"internalType":"address"},{"name":"price","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"timestamp","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"error","name":"NotSentinel","inputs":[]},
  {"type":"error","name":"OnCooldown","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address","internalType":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address","internalType":"address"}]},
  {"type":"error","name":"ThresholdNotMet","inputs":[]},
  {"type":"error","name":"ZeroAddress","inputs":[]},
]
