import type { Abi } from "viem"

export const abi: Abi = [
  {"type":"constructor","inputs":[{"name":"initialOwner","type":"address","internalType":"address"}],"stateMutability":"nonpayable"},
  {"type":"function","name":"addPosition","inputs":[{"name":"trader","type":"address","internalType":"address"},{"name":"collateral","type":"uint256","internalType":"uint256"},{"name":"prefunded","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"gateway","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"getActivePositions","inputs":[{"name":"start","type":"uint256","internalType":"uint256"},{"name":"limit","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"batch","type":"tuple[]","internalType":"struct MockInvalendProtocol.Position[]","components":[{"name":"id","type":"uint256","internalType":"uint256"},{"name":"trader","type":"address","internalType":"address"},{"name":"collateralAmount","type":"uint256","internalType":"uint256"},{"name":"prefundedAmount","type":"uint256","internalType":"uint256"},{"name":"isActive","type":"bool","internalType":"bool"}]},{"name":"total","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"getHealthFactor","inputs":[{"name":"positionId","type":"uint256","internalType":"uint256"}],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"getPoolStats","inputs":[],"outputs":[{"name":"utilization","type":"uint256","internalType":"uint256"},{"name":"liquidity","type":"uint256","internalType":"uint256"},{"name":"borrowed","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"maxLeverageTier","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"newPositionsPaused","inputs":[],"outputs":[{"name":"","type":"bool","internalType":"bool"}],"stateMutability":"view"},
  {"type":"function","name":"owner","inputs":[],"outputs":[{"name":"","type":"address","internalType":"address"}],"stateMutability":"view"},
  {"type":"function","name":"pauseNewPositions","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"reduceMaxLeverage","inputs":[{"name":"newTier","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"renounceOwnership","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"resumeNewPositions","inputs":[],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setGateway","inputs":[{"name":"_gateway","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setPoolStats","inputs":[{"name":"_totalLiquidity","type":"uint256","internalType":"uint256"},{"name":"_totalBorrowed","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"setPositionCollateral","inputs":[{"name":"positionId","type":"uint256","internalType":"uint256"},{"name":"newCollateral","type":"uint256","internalType":"uint256"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"function","name":"totalBorrowed","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"totalLiquidity","inputs":[],"outputs":[{"name":"","type":"uint256","internalType":"uint256"}],"stateMutability":"view"},
  {"type":"function","name":"transferOwnership","inputs":[{"name":"newOwner","type":"address","internalType":"address"}],"outputs":[],"stateMutability":"nonpayable"},
  {"type":"event","name":"GatewaySet","inputs":[{"name":"gateway","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"LeverageReduced","inputs":[{"name":"previousTier","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"newTier","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"OwnershipTransferred","inputs":[{"name":"previousOwner","type":"address","indexed":true,"internalType":"address"},{"name":"newOwner","type":"address","indexed":true,"internalType":"address"}],"anonymous":false},
  {"type":"event","name":"PositionAdded","inputs":[{"name":"id","type":"uint256","indexed":true,"internalType":"uint256"},{"name":"trader","type":"address","indexed":true,"internalType":"address"},{"name":"collateral","type":"uint256","indexed":false,"internalType":"uint256"},{"name":"prefunded","type":"uint256","indexed":false,"internalType":"uint256"}],"anonymous":false},
  {"type":"event","name":"PositionsPaused","inputs":[],"anonymous":false},
  {"type":"event","name":"PositionsResumed","inputs":[],"anonymous":false},
  {"type":"error","name":"GatewayNotSet","inputs":[]},
  {"type":"error","name":"InvalidLeverageTier","inputs":[]},
  {"type":"error","name":"InvalidPositionId","inputs":[]},
  {"type":"error","name":"NotGateway","inputs":[]},
  {"type":"error","name":"OwnableInvalidOwner","inputs":[{"name":"owner","type":"address","internalType":"address"}]},
  {"type":"error","name":"OwnableUnauthorizedAccount","inputs":[{"name":"account","type":"address","internalType":"address"}]},
]
